"""Add load balancer and target tables

Revision ID: 18a831a42368
Revises: f5aa0ae43659
Create Date: 2025-04-16 11:16:46.470856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18a831a42368'
down_revision = 'f5aa0ae43659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
