"""Add ScalingHistory model

Revision ID: 4afa8949b572
Revises: e06e2f5c99ce
Create Date: 2025-04-11 22:01:32.059895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4afa8949b572'
down_revision = 'e06e2f5c99ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scaling_history', sa.Column('metric', sa.String(length=50), nullable=True))
    op.add_column('scaling_history', sa.Column('value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scaling_history', 'value')
    op.drop_column('scaling_history', 'metric')
    # ### end Alembic commands ###
