"""add_instance_and_lxc_profile_tables

Revision ID: 8641b35a1d5b
Revises: d6e95a1b6436
Create Date: 2025-04-17 09:14:57.716410

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8641b35a1d5b'
down_revision = 'd6e95a1b6436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('load_balancer_targets')
    op.drop_table('load_balancers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('load_balancers',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('load_balancers_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('algorithm', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('port', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='load_balancers_pkey'),
    sa.UniqueConstraint('name', name='load_balancers_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('load_balancer_targets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('load_balancer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('container_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('port', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weight', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('health_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('added_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['load_balancer_id'], ['load_balancers.id'], name='load_balancer_targets_load_balancer_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='load_balancer_targets_pkey')
    )
    # ### end Alembic commands ###
