"""Add cpu_usage and memory_usage columns

Revision ID: f5aa0ae43659
Revises: 4afa8949b572
Create Date: 2025-04-14 07:43:21.791326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5aa0ae43659'
down_revision = '4afa8949b572'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
